name: booking_appointments
description: "Appointment booking application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  get_it: ^8.0.3
  go_router: ^15.1.2
  intl: ^0.20.2
  shared_preferences: ^2.5.5

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.8
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
